QuestionNaireMVC4C/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.Text;
using System.IO;
using System.Data;
using Ionic.Zip;



namespace QuestionNaireMVC4C.Controllers
{
    public class Question
    {
        public int id { get; set; }
        public string title { get; set; }
        public string type { get; set; }
        public string options { get; set; }
        public string star_target { get; set; }

    }

    public class QuestionNaire
    {
        public string id { get; set; }
        public string title { get; set; }
        public string introduction { get; set; }
        public List<Question> questions { get; set; }
    }


    public class QResult
    {
        public string type { get; set; }
        public string title { get; set; }
        public string star_target { get; set; }

        public string[,] options { get; set; }
    }
    public class Result
    {
        //参与人数
        public int number { get; set; }
        public string id { get; set; }
        public string title { get; set; }
        public List<QResult> answers { get; set; }
    }

    public class AdminController : Controller
    {
        ///   <summary>
        ///   将指定字符串按指定长度进行剪切，
        ///   </summary>
        ///   <param   name="oldStr "> 需要截断的字符串 </param>
        ///   <param   name="maxLength "> 字符串的最大长度 </param>
        ///   <param   name="endWith "> 超过长度的后缀 </param>
        ///   <returns> 如果超过长度，返回截断后的新字符串加上后缀，否则，返回原字符串 </returns>
        public string StringTruncat(string oldStr, int maxLength = 25, string endWith = "...")
        {
            if (string.IsNullOrEmpty(oldStr))
                //   throw   new   NullReferenceException( "原字符串不能为空 ");
                return oldStr + endWith;
            if (maxLength < 1)
                return "";
            if (oldStr.Length > maxLength)
            {
                string strTmp = oldStr.Substring(0, maxLength);
                if (string.IsNullOrEmpty(endWith))
                    return strTmp;
                else
                    return strTmp + endWith;
            }
            return oldStr;
        }

        /// <summary>
        /// 对datatble的内容进行预处理，以便正常显示。
        /// </summary>
        /// <param name="dt"></param>
        /// <returns></returns>
        public static DataTable FormatDatatable(DataTable dt)
        {
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                for (int j = 0; j < dt.Columns.Count; j++)
                {
                    dt.Rows[i][j] = dt.Rows[i][j].ToString()
                        .Replace("\"", "“")
                        .Replace(",", "，")
                        .Replace("\t", "")
                        .Replace("\n", " ")
                        .Replace("\r", " ");
                }
            }
            return dt;
        }

        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CheckQn()
        {
            string sql = "SELECT id,title,introduction,is_open FROM questionnaire ORDER BY id DESC";
            var questions = DB.GetResult(sql).Rows;
            //防止简介过长，截断
            for (int i = 0; i < questions.Count; i++)
            {
                questions[i][2] = StringTruncat(questions[i][2].ToString());
            }
            ViewBag.questions = questions;

            return View();
        }



        /// <summary>
        /// 获取问卷回答数目。
        /// </summary>
        /// <returns></returns>
        public int getAnswerNumber(string qnid)
        {
            int num = 0;

            string sql = string.Format("SELECT id FROM question WHERE belong_qn='{0}'", qnid);
            var q = DB.GetResult(sql).Rows;
            if (q.Count <= 0)
            {
                //这个问卷没有题。
                num = 0;
            }
            else
            {
                string qid = q[0][0].ToString();
                sql = string.Format("SELECT count(id) FROM answer WHERE belong_q='{0}'", qid);
                string numstr = DB.GetResult(sql).Rows[0][0].ToString();
                num = Int32.Parse(numstr);
            }

            return num;
        }

        /// <summary>
        /// 统计问卷结果
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult CheckQnResult(string id)
        {
            updateStarLevel(id);

            string sql = string.Format("SELECT id,title,introduction,is_open FROM questionnaire WHERE id='{0}'", id);
            var qn = DB.GetResult(sql).Rows[0];
            Result res = new Result();
            res.answers = new List<QResult>();
            res.id = qn[0].ToString();
            res.title = qn[1].ToString();
            res.number = getAnswerNumber(res.id);
            sql = string.Format("SELECT id,introduction,type,options,star_target FROM question WHERE belong_qn='{0}'", res.id);
            var qs = DB.GetResult(sql).Rows;

            for (int i = 0; i < qs.Count; i++)
            {
                QResult qres = new QResult();
                qres.title = qs[i][1].ToString();
                qres.type = qs[i][2].ToString();
                qres.star_target = qs[i][4].ToString();
                string[] qoptions = qs[i][3].ToString().Split(',');
                int onum = qoptions.Length;
                string qid = qs[i][0].ToString();
                switch (qres.type)
                {
                    case "1":
                        //单选
                        qres.options = new string[onum, 2];
                        for (int j = 0; j < onum; j++) qres.options[j, 0] = qoptions[j];
                        int[] times1 = new int[onum];
                        sql = string.Format("SELECT answer FROM answer WHERE belong_q='{0}'", qid);
                        var a1 = DB.GetResult(sql).Rows;
                        for (int k = 0; k < a1.Count; k++)
                        {
                            times1[Int32.Parse(a1[k][0].ToString()) - 1]++;
                        }
                        for (int j = 0; j < onum; j++) qres.options[j, 1] = times1[j].ToString();
                        break;
                    case "2":
                        //多选
                        qres.options = new string[onum, 2];
                        for (int j = 0; j < onum; j++) qres.options[j, 0] = qoptions[j];
                        int[] times2 = new int[onum];
                        sql = string.Format("SELECT answer FROM answer WHERE belong_q='{0}'", qid);
                        var a2 = DB.GetResult(sql).Rows;
                        for (int k = 0; k < a2.Count; k++)
                        {
                            string[] answerstr = a2[k][0].ToString().Split(',');
                            foreach (var ans in answerstr)
                            {
                                int ansint = Int32.Parse(ans);
                                times2[ansint - 1]++;
                            }
                        }
                        for (int j = 0; j < onum; j++) qres.options[j, 1] = times2[j].ToString();
                        break;
                    case "3":
                        //简答题
                        sql = string.Format("SELECT answer FROM answer WHERE belong_q='{0}'", qid);
                        var a4 = DB.GetResult(sql).Rows;
                        qres.options = new string[a4.Count, 1];
                        for (int k = 0; k < a4.Count; k++)
                        {
                            qres.options[k, 0] = a4[k][0].ToString().Replace("\r", "").Replace("\n", "");
                        }

                        break;
                    case "4":
                    case "5":
                        //矩阵单选
                        qres.options = new string[onum, 5];
                        for (int j = 0; j < onum; j++) qres.options[j, 0] = qoptions[j];
                        int[,] times3 = new int[onum, 4];
                        sql = string.Format("SELECT answer FROM answer WHERE belong_q='{0}'", qid);
                        var a = DB.GetResult(sql).Rows;
                        for (int k = 0; k < a.Count; k++)
                        {
                            string[] answerstr = a[k][0].ToString().Split(',');
                            for (int l = 0; l < onum; l++)
                            {
                                int ansint = Int32.Parse(answerstr[l]);
                                times3[l, ansint - 1]++;
                            }
                        }
                        for (int k = 0; k < 4; k++)
                        {
                            for (int j = 0; j < onum; j++) qres.options[j, k + 1] = times3[j, k].ToString();
                        }

                        break;
                    
                    default:
                        break;
                }
                res.answers.Add(qres);
            }
            ViewBag.res = res;
            return View();
        }

        public ActionResult CheckQnPublish(string id)
        {
            string sql = string.Format("SELECT publish_code,title FROM questionnaire WHERE id='{0}'", id);
            var res = DB.GetResult(sql).Rows;
            if (res.Count > 0)
            {
                string code = res[0][0].ToString();
                string name = res[0][1].ToString();
                string url = Url.Action("ShowQnByCode", "Student", new { code = code });
                ViewBag.qnurl = url;
                ViewBag.qnname = name;
            }

            return View();
        }


        public ActionResult CopyQn(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                try
                {
                    int qnid = Int32.Parse(id);
                    string sql = string.Format("SELECT * FROM questionnaire WHERE id='{0}'", qnid);

QuestionNaireMVC4C/Controllers/ProjectUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.Text;
using System.IO;
using System.Data;
using System.Data.Sql;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Collections;
using System.Xml;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using NPOI.HSSF.UserModel;

namespace QuestionNaireMVC4C.Controllers
{
    

    public class ProjectUserController : Controller
    {

        /// <summary>
        /// 对datatble的内容进行预处理，以便正常显示。
        /// </summary>
        /// <param name="dt"></param>
        /// <returns></returns>
        public static DataTable FormatDatatable(DataTable dt)
        {
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                for (int j = 0; j < dt.Columns.Count; j++)
                {
                    dt.Rows[i][j] = dt.Rows[i][j].ToString()
                        .Replace("\"", "“")
                        .Replace(",", "，")
                        .Replace("\t", "")
                        .Replace("\n", " ")
                        .Replace("\r", " ");
                }
            }
            return dt;
        }
        
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 统计教师的完成课程数。更新数据库的存储状态
        /// </summary>
        public static void updateTeacherComplete()
        {
            string sql = "UPDATE K SET Completed=(SELECT count(id) from Class_Teacher_Info WHERE Teachername =K.Teachername) FROM Class_Teacher_Info K";
            DB.ExecuteSql(sql);
        }

        public ActionResult CheckClassInfo()
        {
            updateTeacherComplete();
            string sql = "SELECT id,classnumber,classname,classtime,major,projectname,projectkey,teachername,classeva FROM class_teacher_info";
            var info = DB.GetResult(sql).Rows;
            ViewBag.info = info;

            return View();
        }



        public ActionResult CheckClassInfoDetail(string id = "")
        {
            if (!string.IsNullOrEmpty(id))
            {
                // 编辑数据
                try
                {
                    int info_id = Int32.Parse(id);
                    string sql = string.Format("SELECT * FROM class_teacher_info WHERE id='{0}'", info_id);
                    var info = DB.GetResult(sql);
                    info = FormatDatatable(info);
                    ViewBag.info = info.Rows[0];
                }
                catch
                {

                }
            }
            return View();
        }

        public ActionResult DownloadClassInfo()
        {
            string sql = "select classnumber as '课程编号', classname as '课程名称', classperiod as '课程学时', classtime as '开课时间', major as '所属专业', projectname as '项目名称', projectkey as '项目关键词', projecttype as '项目属性', studenttype as '学院类别', number as '学员人数', teachername as '教师姓名',teacherposition as '教师职称', workplace as '教师所在单位', email as 'Email', phone as '办公电话', telephone as '手机电话', other as '其他联系方式', teacherinfo as '教师简介', completed as '完成授课次数', state as '授课状态', teachereva as '教师综合评价', classinfo as '课程简介', classeva as '课程综合评价'  from class_teacher_info";
            var info = DB.GetResult(sql);
            info = FormatDatatable(info);
            Response.AppendHeader("Content-Disposition", "attachment;filename=" + "课程信息导出.csv");
            Response.Charset = "gb2312";
            Response.ContentEncoding = System.Text.Encoding.GetEncoding("gb2312");
            Response.ContentType = "application/ms-excel";
            Response.Write(ExcelHelper.GetCSVContent(info));
            Response.End();
            return Content("");
        }

    }
}

QuestionNaireMVC4C/Views/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <link href="@Url.Content("~/favicon.ico")" rel="shortcut icon">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>北航软件学院调研系统</title>
    <link href="@Url.Content("~/Content/sb-admin-2.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/bootstrap-theme.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/bower_components/font-awesome/css/font-awesome.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/bower_components/metisMenu/src/metisMenu.css")" rel="stylesheet">

    <script src="@Url.Content("~/Scripts/jquery-3.1.0.min.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>
    <script src="@Url.Content("~/Scripts/sb-admin-2.js")"></script>
    <script src="@Url.Content("~/bower_components/metisMenu/src/metisMenu.js")"></script>
    @*@Styles.Render("~/Content/css")
    @Styles.Render("~/metisMenu/css")
    @Styles.Render("~/font-awesome")
    @Scripts.Render("~/jquery")*@

    @*@Scripts.Render("~/metisMenu/js")*@

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Index","Home")">北航软件学院调研系统 - @ViewBag.Title</a>

            </div>

            @if (!Object.Equals(Session["id"], null))
{
    using (Html.BeginForm("Logout", "Home", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()

        <ul class="nav navbar-nav navbar-right">
            <li>
                @Html.ActionLink("你好, " + Session["name"].ToString() + " !", "Userinfo", "Home")
            </li>
            <li>@Html.ActionLink("修改密码", "Userinfo", "Home")</li>
            <li>@Html.ActionLink("登出", "Logout", "Home")</li>
        </ul>
    }
}
            else
            {
                <script>location.href = "@Url.Content("~")";</script>
            }


            <!-- /.navbar-top-links -->
            <div class="navbar-default sidebar" role="navigation">
                @if (!Object.Equals(Session["id"], null))
{
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            @if (Session["type"].ToString() == "1")
            {
                <li>
                    <a href="@Url.Action("AddClassInfo","Admin")"><i class="fa fa-table fa-fw"></i> 添加课程</a>
                </li>
                <li>
                    <a href="@Url.Action("CheckClassInfo","Admin")"><i class="fa fa-table fa-fw"></i> 查看课程</a>
                </li>
                
                <li style="border-top:2px solid #ccc;"> 
                    <a href="@Url.Action("CheckQn","Admin")"><i class="fa fa-edit fa-fw"></i> 查看问卷</a>
                </li>
                <li>
                    <a href="@Url.Action("AddQn","Admin")"><i class="fa fa-edit fa-fw"></i> 添加问卷</a>
                </li>

    <li style="border-top:2px solid #ccc;">
        <a href="@Url.Action("CheckUser","Admin")"><i class="fa fa-users fa-fw"></i> 用户管理</a>
    </li>
            }
            else if (Session["type"].ToString() == "2")
            {
                <li>
                    <a href="@Url.Action("CheckClassInfo","ProjectUser")"><i class="fa fa-table fa-fw"></i> 查看课程</a>
                </li>
            }
        </ul>
    </div>
}


                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    @RenderBody()
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    @*<!-- jQuery -->
        <script src="../bower_components/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- Metis Menu Plugin JavaScript -->
        <script src="../bower_components/metisMenu/dist/metisMenu.min.js"></script>
        <!-- Custom Theme JavaScript -->
        <script src="../dist/js/sb-admin-2.js"></script>*@
</body>
</html>

QuestionNaireMVC4C/Views/_Layout_student.cshtml
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <link href="@Url.Content("~/favicon.ico")" rel="shortcut icon">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>北航软件学院调研系统</title>
    <link href="@Url.Content("~/Content/sb-admin-2.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/bootstrap-theme.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/bower_components/font-awesome/css/font-awesome.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/bower_components/metisMenu/src/metisMenu.css")" rel="stylesheet">

    <script src="@Url.Content("~/Scripts/jquery-3.1.0.min.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>
    <script src="@Url.Content("~/Scripts/sb-admin-2.js")"></script>
    <script src="@Url.Content("~/bower_components/metisMenu/src/metisMenu.js")"></script>
    @*@Styles.Render("~/Content/css")
    @Styles.Render("~/metisMenu/css")
    @Styles.Render("~/font-awesome")
    @Scripts.Render("~/jquery")*@

    @*@Scripts.Render("~/metisMenu/js")*@

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <!-- Page Content -->
      
            <div class="container-fluid">
                <div class="row">
                    @RenderBody()
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->
 
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    @*<!-- jQuery -->
        <script src="../bower_components/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- Metis Menu Plugin JavaScript -->
        <script src="../bower_components/metisMenu/dist/metisMenu.min.js"></script>
        <!-- Custom Theme JavaScript -->
        <script src="../dist/js/sb-admin-2.js"></script>*@
</body>
</html>